import Head from "next/head";
import { useRouter } from 'next/navigation'
import { useCallback, useState } from 'react';

import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

import { siteConfig } from "@/constant/config";

import style from '@/styles/pages/home.module.scss';

const HomePage = () => {
  const [keyword, setKeyword] = useState('');
  const { push: navigate } = useRouter();

  const searchMusic = useCallback(() => {
    navigate(`list?keyword=${keyword}&limit=4`)
  }, [keyword, navigate]);

  return (
    <>
      <Head>
        <title>Home - {siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={`h-screen flex flex-col justify-between relative px-2 ${style['bg']}`}>

        <div className="flex h-full">
          <img src="/images/logo.webp" alt="simply-music-logo" className="w-[72px] h-[72px] m-auto" />
        </div>

        <div className="flex flex-col px-4 justify-center mb-6 gap-4">
          <Input onChange={(e) => setKeyword(e.target.value)} placeholder="Artist / Album / Title" type="text" className="text-center rounded-3xl" />

          <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2">
            <Button onClick={searchMusic} variant="secondary" className="w-full rounded-3xl" type="submit">Search</Button>
          </div>
        </div>
      </div>
    </>
  )
}


export default HomePage;
