import Head from "next/head";
import { useSearchParams } from 'next/navigation';
import { useQueryState } from "nuqs";
import { useEffect, useState } from "react";
import { useQuery } from 'react-query';

import Header from "@/components/Header";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";

import { siteConfig } from "@/constant/config";
import music from '@/integrations/music';

import { IResponse } from "../../global";

const ListPage = () => {

  const searchParams = useSearchParams();
  const qParamKeyword = searchParams.get('keyword');
  const qParamLimit = searchParams.get('limit');
  const [limit, setLimit] = useQueryState('limit');
  const [cacheValue, setCacheValue] = useState({keyword: '', limit: ''});


  
  const loadMore = () => {
    const newLimit = `${Number(qParamLimit) + Number(qParamLimit)}`;
    setLimit(newLimit);
  };

  const { data = { results: [] }, isLoading } = useQuery({
    queryKey: ['musicList'],
    refetchOnWindowFocus: false,
    queryFn: async () => {
      const keyword = qParamKeyword.replace(/\s+/g, '+');
      const data = await music.getList<IResponse>({ term: keyword, limit: limit });

      return data
    },
    enabled: cacheValue?.keyword !== qParamKeyword || cacheValue?.limit !== qParamLimit
  });

  useEffect(() => {
    setCacheValue({keyword: qParamKeyword, limit: qParamLimit})
    console.log('🚀 ~ {keyword: qParamKeyword, limit: qParamLimit}:', {keyword: qParamKeyword, limit: qParamLimit});
  }, [qParamKeyword, qParamLimit]);

  return (
    <>
      <Head>
        <title>List - {siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <div className="bg-slate-100 min-h-screen pt-6 px-5 pb-16 lg:grid lg:max-w-7xl lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:pt-5">

        <h1 className="text-sm text-center">Search result for: <span className="text-lg font-bold text-violet-700">{qParamKeyword}</span></h1>
        
        <div className="pt-5">
          {
            isLoading ? (
              <div>
                Loading...
              </div>
            ) : (
              data.results.length > 0 ? (
                <div className="flex flex-col">
                  {
                    data.results.map((record) => (
                      <Card key={record.trackName} className="w-full mb-5 p-3">
                        <div className="flex">
                          <img src={record.artworkUrl100} className="w-[100px] rounded-xl" />
                          <div className="flex flex-auto flex-col justify-between px-4">
                            <div className="flex flex-col">
                              <span className="text-[10px] font-semibold">{record.artistName}</span>
                              <h4 className="font-bold text-sm">{record.trackName}</h4>
                            </div>

                            <div className="flex justify-between">
                              {/* Tag */}
                              <div className="px-2 bg-emerald-500 min-w-[45px] items-center flex justify-center text-white rounded-xl text-[10px]">
                                {record.primaryGenreName}
                              </div>

                              <div className="flex items-center text-sm text-amber-500">
                                <img src="/icons/dollar-currency.webp" alt="price-sign" className="w-[16px] h-[16px]" />
                                <span className="ml-1">{record.trackPrice}</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </Card>
                    ))
                  }
                  <div className="m-auto">
                    <Button onClick={() => loadMore()} variant="secondary" className="px-8 text-slate-500 bg-slate-200 rounded-3xl">
                      Load More
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="flex-col border rounded p-3">
                  <p className="text-center" style={{ whiteSpace: 'pre-line' }}>
                    Not music yet
                  </p>
                </div>
              )
            )
          }
        </div>

      </div>
    </>
  )
}


export default ListPage;
